version: '2'

networks:
  goapp-network:
    driver: bridge

services:
  nginx:
    image: server/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
  go1:
    image: server/golang
    container_name: go1
    ports:
      - "8080"
    networks:
      - goapp-network
