language: generic
sudo: required
install: true

os:
  - linux

env:
  global:
    - GIMME_OS=linux GIMME_ARCH=amd64 GIMME_GO_VERSION=1.7.3
    - NODE_VERSION=6.9.1
    - PROJECT="$PWD"
    - FRONTEND="$PROJECT/frontend"
    - BACKEND="$PROJECT/backend"

addons:
  hosts:
    - postgres
    - mongodb
    - nginx
    - go1
    - gon
    - api.lp4adev.tk
    - www.lp4adev.tk
    - lp4adev.tk
    - api.lp4a.tk
    - www.lp4a.tk
    - lp4a.tk
    - api.lp4astaging.tk
    - www.lp4astaging.tk
    - lp4astaging.tk

before_install:
  - eval "$(gimme)"
  - nvm install "$NODE_VERSION"
  - nvm use "$NODE_VERSION"

before_script:
  - npm install -g angular-cli
  - go get github.com/constabulary/gb/...

script:
   - cd "$FRONTEND"
   - npm install
   - node_modules/karma/bin/karma start karma.conf.js --single-run
   - cd "$BACKEND"
   - gb vendor restore
   - gb test server

notifications:
  slack: ldso51:sq2rhGIJnWafmF0MWN2phN3W

services:
  - docker
