language: generic 
sudo: required
install: true

os:
  - linux

branches:
  only:
    - migrationCSS
    - migration
    - imagesGoPostgres 
    - development	

env:
  global:
    - GIMME_OS=linux GIMME_ARCH=amd64 GIMME_GO_VERSION=1.7.3
    - IMAGE_NAME=tsuru/api
    - NODE_VERSION=6.9.1
    - PROJECT="$PWD" 
    - FRONTEND="$PROJECT/frontend"
    - BACKEND="$PROJECT/backend"

addons:
  hosts:
    - postgres
    - mongodb
    - nginx
    - go1
    - gon
    - api.lp4adev.tk
    - www.lp4adev.tk
    - lp4adev.tk
    - api.lp4a.tk
    - www.lp4a.tk
    - lp4a.tk
    - api.lp4astaging.tk
    - www.lp4astaging.tk
    - lp4astaging.tk
  apt:
    packages:
      - postgresql-9.6
      - postgresql-contrib-9.6

before_install:
  - eval "$(gimme)"
  - nvm install "$NODE_VERSION"
  - nvm use "$NODE_VERSION"

before_script:
  - npm install -g angular-cli
  - go get github.com/constabulary/gb/...
  - sudo service postgresql stop

script:
   - postgres_bin="/usr/lib/postgresql/9.6/bin/"
   - export PATH="$PATH:$postgres_bin"
   - cd "$FRONTEND"
   - npm install
   - node_modules/karma/bin/karma start karma.conf.js --single-run
   - cd "$BACKEND"
   - gb vendor restore
   - gb build server
   - gb test server
   - cd "$DATABASE"
   - ./pgr initddl
   - cd "$BACKEND"
   - ./bin/server &
   - cd "$API_TESTS"
   - ./apiTests.sh noinit

before_install:
  - eval "$(gimme)"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - go get github.com/constabulary/gb/...
script:
   - cd "$FRONTEND" 
   - npm install -g angular-cli  
   - npm install
   #- ng test
   - cd "$BACKEND" 
   - gb vendor restore
   - gb test server

notifications:
  slack: ldso51:CK9j3GCfFoj0QpTTTxDdt8lZ

services:
  - docker
  - mongodb
