sudo: required
dist: trusty

language: generic

env:
  global:
    - GOLANG_VERSION="1.7.3"
    - GOLANG_DOWNLOAD_SHA256="508028aac0654e993564b6e2014bf2d4a9751e3b286661b0b0040046cf18028e"

services:
  - docker
  - mongodb
  - redis-server

addons:
  hosts:
    - mongodb
    - nginx
    - go1
    - gon
    - api.lp4adev.tk
    - www.lp4adev.tk
    - lp4adev.tk
    - api.lp4a.tk
    - www.lp4a.tk
    - lp4a.tk

before_install: .ci/before_install.sh
install:        .ci/install.sh
before_script:  .ci/before_script.sh
script:         .ci/script.sh
after_success:  .ci/after_success.sh
after_failure:  .ci/after_failure.sh
before_deploy:  .ci/before_deploy.sh
deploy:         .ci/deploy.sh
