#!/usr/bin/env bash

main() {
  if [[ $# -ne 1 ]]; then
    1>&2 echo "only one argument allowed"
    exit 1
  fi

  case $1 in
    build|run)
      $1
      ;;
    *)
      1>&2 echo "option doesnt exist"
      exit 1
  esac
}

build() {
  tar -cf - --exclude-ignore-recursive=exclude_docker_build . | docker build -t server/golangangular -
}

run() {
  docker run --rm -p 8080:8888 server/golangangular
}

main "$@"
