#!/usr/bin/env bash

script_dir="${0%/*}"
cd "$script_dir"

main() {
  clone pressly/chi
  clone SermoDigital/jose
}

clone() {
  regex='[^/]+/[^/]+'
  if [[ "$#" -ne 1 || ! ( "$1" =~ $regex ) ]]; then
    1>&2 echo -e "${0##*/}" FAILED: "$FUNCNAME" "${1:-user/repo}"
    return
  fi

  dir="vendor/src/github.com/$1"
  if [[ -d "$dir/.git" ]]; then
    echo "Updating $1"
    old_dir=$(pwd)
    cd "$dir"
    git pull
    cd "$old_dir"
    echo
  else
    echo "Cloning $1"
    git clone "https://github.com/$1" "$dir"
    echo
  fi
}

main "$@"
