#!/usr/bin/env bash

shopt -s expand_aliases

case "$(uname -s)" in
    "Darwin")
    alias timeout='/usr/local/bin/gtimeout'
    alias sort='/usr/local/bin/gsort'
    ;;
esac

set -e

cd "${0%/*}"

usage="$0 (init|start|stop|restart|ddl|examples|initddl [file])"
cluster_dir="./cluster"
timeout_duration="10"
db_name="places4all"
schema_name="places4all"
sql_dir="./sql"
examples_dir="$sql_dir/examples"

main() {
  if [[ $# -lt 1 ]]; then
    1>&2 echo "$usage"
    exit 1
  fi

  case "$1" in
    init|start|stop|restart|ddl|examples|initddl|initddlexamples)
      "$1" "${@:2}"
      ;;
    *)
      1>&2 echo "$usage"
      exit 1
  esac
}

init() {
  if [[ $# -ne 0 ]]; then
    exit 1
  fi

  case "$(uname -s)" in
    "Linux")
      local postgresPidFolder="/run/postgresql"
      sudo mkdir -p "$postgresPidFolder"
      sudo chown -R "$USER:$USER" "$postgresPidFolder"
      ;;
  esac

  stop || true
#  timeout "$timeout_duration" killall postgres --wait || true
  rm -rf "$cluster_dir" || true
  mkdir -p "$cluster_dir"
  initdb --pgdata "$cluster_dir" --locale="en_US.UTF-8" --encoding="UTF8"
  pg_ctl start --pgdata "$cluster_dir"
  sleep 3
  createdb "$db_name"
}

start() {
  pg_ctl start --pgdata "$cluster_dir" "$@"
}

stop() {
  pg_ctl stop --pgdata "$cluster_dir" "$@"
}

restart() {
  pg_ctl restart --pgdata "$cluster_dir" "$@"
}

ddl() {
  if [[ $# -ne 0 ]]; then
    exit 1
  fi

  find "$sql_dir" -maxdepth 1 -type f -iname "*.sql" -print0 | sort -z -V | while read -d $'\0' sql
  do
    psql "$db_name" -f "$sql"
  done
}

examples() {
  if [[ $# -gt 1 ]]; then
    exit 1
  fi

  if [[ $# -eq 0 ]]; then
    find "$examples_dir" -type f -iname "*.sql" -print0 | sort -z -V | while read -d $'\0' sql
    do
      echo "$sql"
      psql "$db_name" -f "$sql"
    done
  else
    files=("$examples_dir"/*"$1"*)
    echo "${files[@]}"
    [[ ${#files[@]} -ne 1 ]] && 1>&2 echo 'too many files' && exit 1
    psql "$db_name" -f "${files[0]}"
  fi
}

initddl() {
    init && ddl
}

initddlexamples() {
    init && ddl && examples
}

main "$@"
