#!/usr/bin/env bash

set -e

cd "${0%/*}"

usage="$0 (init|start|stop|restart)"
cluster_dir="./cluster"
timeout_duration="10"
db_name="places4all"

main() {
  if [[ $# -ne 1 ]]; then
    1>&2 echo "$usage"
    exit 1
  fi

  case "$1" in
    init|start|stop|restart)
      "$1"
      ;;
    *)
      1>&2 echo "$usage"
      exit 1
  esac
}

init() {
  stop || true
  timeout "$timeout_duration" killall postgres --wait || true
  rm -rf "$cluster_dir" || true
  mkdir -p "$cluster_dir"
  pg_ctl init --pgdata "$cluster_dir" -o '--locale="en_US.UTF-8" --encoding="UTF8"'
  pg_ctl start --pgdata "$cluster_dir"
  cd "$cluster_dir"
  createuser --superuser --pwprompt --echo admin
  createdb "$db_name" --username admin
}

start() {
  pg_ctl start --pgdata "$cluster_dir"
}

stop() {
  pg_ctl stop --pgdata "$cluster_dir"
}

restart() {
  pg_ctl restart --pgdata "$cluster_dir"
}

main "$@"
