version: '2'

networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: prod/nginx
    container_name: nginx
    environment:
      - BUILD=stag
    depends_on:
      - go1
      - gon
    ports:
      - "80:80"
      - "443:443"
    entrypoint:
      - dockerize
      - -template
      - /etc/nginx/nginx.tmpl:/etc/nginx/nginx.conf
      - -wait
      - tcp://go1:8080
      - -wait
      - tcp://gon:8080
      - -timeout
      - 60s
      - nginx
      - -g
      - daemon off;
    networks:
      - app-network
    restart: always
  go1:
    image: prod/golang
    container_name: go1
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    restart: always
  gon:
    image: prod/golang
    container_name: gon
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app-network
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    restart: always
  # mongodb:
  #   image: prod/mongodb
  #   container_name: mongodb
  #   ports:
  #     - "27017"
  #   networks:
  #     - app-network
  # redis:
  #   image: prod/redis
  #   container_name: redis
  #   ports:
  #     - "6379"
  #   networks:
  #     - app-network
