#!/usr/bin/env bash

set -e

main() {

surround_start=";;;;; ADDED BY DEBIAN BASED TOOLS"
surround_end=";;;;; END OF DEBIAN BASED TOOLS"

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y build-essential curl git
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

go_folder='$HOME/golang'
prefix='$HOME/.node-global-packages'
prefix_bin="$prefix/bin"
export_prefix="export PREFIX=\"$prefix\""
export_go="export GOPATH=\"$go_folder\""
export_path="export PATH=\"$prefix_bin:$go_folder/bin:"'$PATH"'

eval mkdir -p "$go_folder"
eval mkdir -p "$prefix_bin"
eval "$export_go"
eval "$export_prefix"
eval "$export_path"

npm install -g yarn
yarn global add angular-cli

remove_around "$surround_start" "$surround_end" "$HOME/.bashrc"

echo "$surround_start" >> "$HOME/.bashrc"
echo -e "$export_go\n$export_path\n$export_prefix" >> "$HOME/.bashrc"
nix_init_script='$HOME/.nix-profile/etc/profile.d/nix.sh'
cat << EOF >> "$HOME/.bashrc"
nix_init_script="$nix_init_script"
EOF
cat << 'EOF' >> "$HOME/.bashrc"
if [[ -f "$nix_init_script" ]]; then
  source "$nix_init_script"
fi
EOF
echo "$surround_end" >> "$HOME/.bashrc"

bash <(curl https://nixos.org/nix/install)

eval source "$nix_init_script"
nix-env -i go watchman

go get github.com/constabulary/gb/...

echo
echo '** Please reboot the computer **'
}

remove_around() {
  if [[ $# -ne 3 ]]; then
    exit 1
  fi
  if [[ -f "$3" ]]; then
    sed -i "/$1/,/$2/d" "$3"
  fi
}

main "$@"
